services:

    _defaults:
        public: true

    elife.api_validator.validator:
        class: eLife\ApiValidator\MessageValidator\JsonMessageValidator
        arguments:
          - '@elife.api_validator.schema_finder'
          - '@elife.api_validator.schema_validator'
        tags:
          - name: optional

    elife.api_validator.validator.fake_https:
        class: eLife\ApiValidator\MessageValidator\FakeHttpsMessageValidator
        decorates: elife.api_validator.validator
        arguments:
          - '@elife.api_validator.validator.fake_https.inner'
        tags:
          - name: optional

    elife.api_validator.schema_validator:
        class: JsonSchema\Validator
        public: false
        tags:
          - name: optional

    elife.api_validator.schema_finder:
        class: eLife\ApiValidator\SchemaFinder\PathBasedSchemaFinder
        public: false
        arguments:
          - '@=composer_locate("elife/api")~"/dist/model"'
        tags:
          - name: optional

    elife.guzzle.middleware.mock.storage:
        class: Csa\Bundle\GuzzleBundle\Cache\MockStorageAdapter
        arguments:
          - '%api_mock%'
          - ['authorization', 'content-length', 'host', 'referer', 'user-agent', 'x-guzzle-cache']

    elife.guzzle.middleware.mock.storage.validating:
        class: test\eLife\Journal\ValidatingStorageAdapter
        decorates: elife.guzzle.middleware.mock.storage
        arguments:
          - '@elife.guzzle.middleware.mock.storage.validating.inner'
          - '@elife.api_validator.validator'
        tags:
          - name: optional

    elife.guzzle.middleware.mock.storage.normalizing:
        class: eLife\Journal\Guzzle\NormalizingStorageAdapter
        decorates: elife.guzzle.middleware.mock.storage
        arguments:
          - '@elife.guzzle.middleware.mock.storage.normalizing.inner'

    elife.guzzle.middleware.mock:
        class: Csa\Bundle\GuzzleBundle\GuzzleHttp\Middleware\MockMiddleware
        arguments:
          - '@elife.guzzle.middleware.mock.storage'
          - replay
        tags:
          - name: csa_guzzle.middleware
            alias: mock
            priority: -1501

    elife.journal.google_client.opt_out_unsubscribe_reason:
        class: test\eLife\Journal\GoogleClient\MockOptoutUnsubscribeReason
